trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - '*.rst'
    - '*.md'
pr:
  paths:
    exclude:
    - '*.rst'
    - '*.md'

jobs:  
- job: 'Validate'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
  - script: |
      pip install -r requirements-dev.txt
      invoke lint
    displayName: 'lint'

- job: 'Test'
  dependsOn: 'Validate'
  strategy:
    matrix:
      Python36Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.6'
      Python36Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.6'
      Python36Mac:
        imageName: 'macos-10.14'
        python.version: '3.6'
      Python37Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.7'
      Python37Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.7'
      Python37Mac:
        imageName: 'macos-10.14'
        python.version: '3.7'
      Python38Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.8'
      Python38Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.8'
      Python38Mac:
        imageName: 'macos-10.14'
        python.version: '3.8'
      Python39Linux:
        imageName: 'ubuntu-16.04'
        python.version: '3.9'
      Python39Windows:
        imageName: 'vs2017-win2016'
        python.version: '3.9'
      Python39Mac:
        imageName: 'macos-10.14'
        python.version: '3.9'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install -U pip setuptools
    displayName: 'Update pip'

  - script: pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: invoke test
    displayName: 'Run tests'

  - script: invoke docs
    displayName: 'Build docs'

  - script: invoke clean
    displayName: 'Clean'